# Generated by Django 4.2.1 on 2023-06-23 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0002_remove_kino_aktyorlar_kino_aktyorlar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izoh',
            name='kino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kinolar', to='app1.kino'),
        ),
        migrations.AlterField(
            model_name='izoh',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kino',
            name='aktyorlar',
            field=models.ManyToManyField(related_name='aktyor', to='app1.aktyor'),
        ),
    ]
